import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Pokemon } from '../pokemons/entities/pokemon.entity';

@Injectable()
export class SeederService {
  private readonly logger = new Logger('SeederService');

  constructor(
    @InjectRepository(Pokemon)
    private readonly pokemonsRepository: Repository<Pokemon>,
  ) {}

  async seedPokemons() {
    try {
      await this.pokemonsRepository.deleteAll();

      const pokemons = [
        { no: 1, name: 'bulbasaur' },
        { no: 2, name: 'ivysaur' },
        { no: 3, name: 'venusaur' },
        { no: 4, name: 'charmander' },
        { no: 5, name: 'charmeleon' },
        { no: 6, name: 'charizard' },
        { no: 7, name: 'squirtle' },
        { no: 8, name: 'wartortle' },
        { no: 9, name: 'blastoise' },
        { no: 10, name: 'caterpie' },
        { no: 11, name: 'metapod' },
        { no: 12, name: 'butterfree' },
        { no: 13, name: 'weedle' },
        { no: 14, name: 'kakuna' },
        { no: 15, name: 'beedrill' },
        { no: 16, name: 'pidgey' },
        { no: 17, name: 'pidgeotto' },
        { no: 18, name: 'pidgeot' },
        { no: 19, name: 'rattata' },
        { no: 20, name: 'raticate' },
        { no: 21, name: 'spearow' },
        { no: 22, name: 'fearow' },
        { no: 23, name: 'ekans' },
        { no: 24, name: 'arbok' },
        { no: 25, name: 'pikachu' },
        { no: 26, name: 'raichu' },
        { no: 27, name: 'sandshrew' },
        { no: 28, name: 'sandslash' },
        { no: 29, name: 'nidoran-f' },
        { no: 30, name: 'nidorina' },
        { no: 31, name: 'nidoqueen' },
        { no: 32, name: 'nidoran-m' },
        { no: 33, name: 'nidorino' },
        { no: 34, name: 'nidoking' },
        { no: 35, name: 'clefairy' },
        { no: 36, name: 'clefable' },
        { no: 37, name: 'vulpix' },
        { no: 38, name: 'ninetales' },
        { no: 39, name: 'jigglypuff' },
        { no: 40, name: 'wigglytuff' },
        { no: 41, name: 'zubat' },
        { no: 42, name: 'golbat' },
        { no: 43, name: 'oddish' },
        { no: 44, name: 'gloom' },
        { no: 45, name: 'vileplume' },
        { no: 46, name: 'paras' },
        { no: 47, name: 'parasect' },
        { no: 48, name: 'venonat' },
        { no: 49, name: 'venomoth' },
        { no: 50, name: 'diglett' },
        { no: 51, name: 'dugtrio' },
        { no: 52, name: 'meowth' },
        { no: 53, name: 'persian' },
        { no: 54, name: 'psyduck' },
        { no: 55, name: 'golduck' },
        { no: 56, name: 'mankey' },
        { no: 57, name: 'primeape' },
        { no: 58, name: 'growlithe' },
        { no: 59, name: 'arcanine' },
        { no: 60, name: 'poliwag' },
        { no: 61, name: 'poliwhirl' },
        { no: 62, name: 'poliwrath' },
        { no: 63, name: 'abra' },
        { no: 64, name: 'kadabra' },
        { no: 65, name: 'alakazam' },
        { no: 66, name: 'machop' },
        { no: 67, name: 'machoke' },
        { no: 68, name: 'machamp' },
        { no: 69, name: 'bellsprout' },
        { no: 70, name: 'weepinbell' },
        { no: 71, name: 'victreebel' },
        { no: 72, name: 'tentacool' },
        { no: 73, name: 'tentacruel' },
        { no: 74, name: 'geodude' },
        { no: 75, name: 'graveler' },
        { no: 76, name: 'golem' },
        { no: 77, name: 'ponyta' },
        { no: 78, name: 'rapidash' },
        { no: 79, name: 'slowpoke' },
        { no: 80, name: 'slowbro' },
        { no: 81, name: 'magnemite' },
        { no: 82, name: 'magneton' },
        { no: 83, name: 'farfetchd' },
        { no: 84, name: 'doduo' },
        { no: 85, name: 'dodrio' },
        { no: 86, name: 'seel' },
        { no: 87, name: 'dewgong' },
        { no: 88, name: 'grimer' },
        { no: 89, name: 'muk' },
        { no: 90, name: 'shellder' },
        { no: 91, name: 'cloyster' },
        { no: 92, name: 'gastly' },
        { no: 93, name: 'haunter' },
        { no: 94, name: 'gengar' },
        { no: 95, name: 'onix' },
        { no: 96, name: 'drowzee' },
        { no: 97, name: 'hypno' },
        { no: 98, name: 'krabby' },
        { no: 99, name: 'kingler' },
        { no: 100, name: 'voltorb' },
        { no: 101, name: 'electrode' },
        { no: 102, name: 'exeggcute' },
        { no: 103, name: 'exeggutor' },
        { no: 104, name: 'cubone' },
        { no: 105, name: 'marowak' },
        { no: 106, name: 'hitmonlee' },
        { no: 107, name: 'hitmonchan' },
        { no: 108, name: 'lickitung' },
        { no: 109, name: 'koffing' },
        { no: 110, name: 'weezing' },
        { no: 111, name: 'rhyhorn' },
        { no: 112, name: 'rhydon' },
        { no: 113, name: 'chansey' },
        { no: 114, name: 'tangela' },
        { no: 115, name: 'kangaskhan' },
        { no: 116, name: 'horsea' },
        { no: 117, name: 'seadra' },
        { no: 118, name: 'goldeen' },
        { no: 119, name: 'seaking' },
        { no: 120, name: 'staryu' },
        { no: 121, name: 'starmie' },
        { no: 122, name: 'mr-mime' },
        { no: 123, name: 'scyther' },
        { no: 124, name: 'jynx' },
        { no: 125, name: 'electabuzz' },
        { no: 126, name: 'magmar' },
        { no: 127, name: 'pinsir' },
        { no: 128, name: 'tauros' },
        { no: 129, name: 'magikarp' },
        { no: 130, name: 'gyarados' },
        { no: 131, name: 'lapras' },
        { no: 132, name: 'ditto' },
        { no: 133, name: 'eevee' },
        { no: 134, name: 'vaporeon' },
        { no: 135, name: 'jolteon' },
        { no: 136, name: 'flareon' },
        { no: 137, name: 'porygon' },
        { no: 138, name: 'omanyte' },
        { no: 139, name: 'omastar' },
        { no: 140, name: 'kabuto' },
        { no: 141, name: 'kabutops' },
        { no: 142, name: 'aerodactyl' },
        { no: 143, name: 'snorlax' },
        { no: 144, name: 'articuno' },
        { no: 145, name: 'zapdos' },
        { no: 146, name: 'moltres' },
        { no: 147, name: 'dratini' },
        { no: 148, name: 'dragonair' },
        { no: 149, name: 'dragonite' },
        { no: 150, name: 'mewtwo' },
      ];

      await this.pokemonsRepository.insert(pokemons);

      this.logger.log(`Successfully seeded ${pokemons.length} pokemons`);

      return { message: `Successfully seeded ${pokemons.length} pokemons` };
    } catch (error) {
      this.logger.error(error);
      throw error;
    }
  }
}
